add hoken
s1F102200794/rent_checker_static pull request #13
Opened 2024-10-17 23:03 UTC by s1f102200570

2024-10-18 04:59 UTC, s1F102200794 requested changes
pタグを`<p>`じゃなくて`<p class="text-gray-600 mb-5 px-6">`で全部書いてほしい。この書き方だとテキストの色とマージンとか(余白)のcssを適応してるから。
ただ、`<p class="text-gray-600 mb-5 px-6">`だと別のpタグにすると上下に余白が出来るから、場合によっては`<br>`を使って改行してほしい。
例
現状の書き方
<p>文章<br>文章</p>

新しい書き方
<p class="text-gray-600 mb-5 px-6">文章</p>
<p class="text-gray-600 mb-5 px-6">文章</p>

2024-10-18 06:11 UTC, s1f102200570 commented
<p>タグの修正
それに伴う改行は特になかった

2024-10-18 06:55 UTC, s1F102200794 requested changes
行間が空きすぎちゃってるからその部分の修正と、不要なpタグの削除をお願いします。

2024-10-18 06:55 UTC, s1F102200794 commented on hoken.html
> +            <p class="text-gray-600 mb-5 px-6"></p>
こことか使ってないところにpタグが乱立してるからいらないなら消してほしい

2024-10-18 07:18 UTC, s1f102200570 commented on hoken.html
> +            <p class="text-gray-600 mb-5 px-6"></p>
行間の空白とか好みで広げてたけど、やりたいこと把握できたのでその形にしました

2024-10-18 09:10 UTC, s1F102200794 requested changes
要らない部分のdivを消してほしい。
最初のdivは必要だけど、他はいらない。
自分で書いたdivは残してもいいけど
`<div class="container px-3 mx-auto flex-wrap flex-col md:flex-row items-center">`
のがいらないかな

2024-10-18 09:13 UTC, s1F102200794 requested changes
これもあったわ

2024-10-18 09:13 UTC, s1F102200794 commented on hoken.html
> +              <br>家財保険の補償額は世帯人数や部屋の広さに応じた目安で決まるが、シンプルな補償で済む場合もある<
あと、ここの「<」を消してほしい

2024-10-21 04:02 UTC, s1F102200794 approved these changes
おっけー

2024-10-21 04:03 UTC, merged